# Generated by Django 5.2 on 2025-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='visit_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='diagnosis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='doctor_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='report',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='user',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
